var myName = "john";
var score1 = 50;
var score2 = 42.50;
var sum = score1 + score2;
console.log("Name: " + myName);
console.log("First Score: " + score1);
console.log("Second Score: " + score2);
console.log("Sum Of Score: " + sum);
var star = "1";
var star1 = star;
console.log(typeof (star1));
